apiVersion: v2
name: salt-master
description: "SaltStack Server in Kubernetes - salt-master instance"

type: application
version: 0.2.0
appVersion: "3004.6"

dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.3.0
