---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
spec:
  storageClassName: {{ .Values.global.persitence.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
